<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>QbAutopost.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QbAutopost.Core\QbAutopost.Core.csproj" />
    <ProjectReference Include="..\QbAutopost.QuickBooks\QbAutopost.QuickBooks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

</Project>
